DEFINT A-Z
DECLARE SUB CHANGE.ITEM (X%, Y%)
DECLARE SUB EDIT.SWITCH (KEYB%, X%, Y%)
DECLARE SUB EDIT.WARP (KEYB%, X%, Y%)
DECLARE SUB INPUTBOX (MESSAGE$, LENTH%, ECHO%, ENTER%, LETTERS%, NUMBERS%, SPACE%, FLAG%)
DECLARE SUB ITEM.SCAN (FLAG&)
DECLARE SUB LOAD.MAP ()
DECLARE SUB MAINLOOP ()
DECLARE SUB NEW.MAP ()
DECLARE SUB SAVE.MAP (FLAG%)
DECLARE SUB SHOW.ITEM (X%, Y%)
DECLARE SUB SHOW.ME ()
DECLARE SUB SHOW.SWITCH ()
DECLARE SUB SHOW.WARP ()
DECLARE SUB START ()
DECLARE SUB UPDATE.ROOM (X%, Y%)
DECLARE SUB WAIT.FOR.KEY.RELEASE (KEYB%)
COMMON SHARED EXIT$, NAME$, FILENAME$, FILE.ERR%, CHANGES.MADE%, GO%, WORKING.FILE$
COMMON SHARED MODE%
DIM SHARED CHART&(20, 21)
DIM SHARED BOX%(5761)
CLEAR
START
CLEAR
DEF SEG = 0
POKE 1047, PEEK(1047) AND 112
SYSTEM
NEW.FILE:
FILE.ERR% = 1
RESUME NEXT

SUB CHANGE.ITEM (X%, Y%)
IF CHART&(0, 2) = X% AND CHART&(0, 3) = Y% THEN
NAME$ = "WARP START ALREADY IN ROOM!  PRESS ENTER."
INPUTBOX NAME$, 0, 0, 1, 0, 0, 0, 2
EXIT SUB
END IF
IF CHART&(0, 4) = X% AND CHART&(0, 5) = Y% THEN
NAME$ = "WARP DESTINATION ALREADY IN ROOM!  PRESS ENTER."
INPUTBOX NAME$, 0, 0, 1, 0, 0, 0, 2
EXIT SUB
END IF
CHANGES.MADE% = 1
IF CHART&(X%, Y%) < 16 GOTO NO.BIT
IF (CHART&(X%, Y%) AND 16) = 16 THEN BIT& = 16
IF (CHART&(X%, Y%) AND 32) = 32 THEN BIT& = 32
IF (CHART&(X%, Y%) AND 64) = 64 THEN BIT& = 64
IF (CHART&(X%, Y%) AND 128) = 128 THEN BIT& = 128
IF (CHART&(X%, Y%) AND 256) = 256 THEN BIT& = 256
IF (CHART&(X%, Y%) AND 512) = 512 THEN BIT& = 512
IF (CHART&(X%, Y%) AND 1024) = 1024 THEN BIT& = 1024
IF (CHART&(X%, Y%) AND 2048) = 2048 THEN BIT& = 2048
IF (CHART&(X%, Y%) AND 4096) = 4096 THEN BIT& = 4096
IF (CHART&(X%, Y%) AND 8192) = 8192 THEN BIT& = 8192
IF (CHART&(X%, Y%) AND 16384) = 16384 THEN BIT& = 16384
BIT& = BIT& + BIT&
NO.BIT:
IF BIT& = 0 THEN BIT& = 16
IF BIT& = 32768 THEN BIT& = 0
CHART&(X%, Y%) = (CHART&(X%, Y%) AND 15) + BIT&
END SUB

SUB EDIT.SWITCH (KEYB%, X%, Y%)

END SUB

SUB EDIT.WARP (KEYB%, X%, Y%)
IF CHART&(0, 2) = X% AND CHART&(0, 3) = Y% THEN
NAME$ = "REMOVE WARP ENTRANCE FROM THIS ROOM?(Y/N)."
INPUTBOX NAME$, 1, 0, 0, 1, 0, 0, 2
IF EXIT$ <> "Y" THEN EXIT SUB
CHART&(CHART&(0, 2), CHART&(0, 3)) = CHART&(CHART&(0, 2), CHART&(0, 3)) AND 15
CHART&(0, 2) = 0
CHART&(0, 3) = 0
END IF
IF CHART&(0, 4) = X% AND CHART&(0, 5) = Y% THEN
NAME$ = "REMOVE WARP DESTINATION FROM THIS ROOM?(Y/N)."
INPUTBOX NAME$, 1, 0, 0, 1, 0, 0, 2
IF EXIT$ <> "Y" THEN EXIT SUB
CHART&(CHART&(0, 4), CHART&(0, 5)) = CHART&(CHART&(0, 4), CHART&(0, 5)) AND 15
CHART&(0, 4) = 0
CHART&(0, 5) = 0
END IF
IF CHART&(X%, Y%) > 15 THEN
NAME$ = "ANOTHER ITEM ALREADY IN ROOM!  PRESS ENTER."
INPUTBOX NAME$, 0, 0, 1, 0, 0, 0, 2
EXIT SUB
END IF
CHANGES.MADE% = 1
IF KEYB% = 2 THEN
CHART&(0, 2) = X%
CHART&(0, 3) = Y%
CHART&(CHART&(0, 2), CHART&(0, 3)) = (CHART&(CHART&(0, 2), CHART&(0, 3)) AND 15) + 32768
NAME$ = "WARP ZONE ENTRANCE IS NOW IN THIS ROOM!  PRESS ENTER."
INPUTBOX NAME$, 0, 0, 1, 0, 0, 0, 2
GO% = 2
END IF
IF KEYB% = 3 THEN
CHART&(0, 4) = X%
CHART&(0, 5) = Y%
CHART&(CHART&(0, 4), CHART&(0, 5)) = (CHART&(CHART&(0, 4), CHART&(0, 5)) AND 15) + 65536
NAME$ = "WARP ZONE DESTINATION IS NOW IN THIS ROOM!  PRESS ENTER."
INPUTBOX NAME$, 0, 0, 1, 0, 0, 0, 2
GO% = 2
END IF
END SUB

SUB INPUTBOX (MESSAGE$, LENTH%, ECHO%, ENTER%, LETTERS%, NUMBERS%, SPACE%, FLAG%)
IF LENTH% = 0 AND ENTER% = 0 THEN EXIT$ = CHR$(1): EXIT SUB
IF LEN(MESSAGE$) + LENTH% > 75 THEN EXIT$ = CHR$(1): EXIT SUB
EXIT$ = ""
IF FLAG% = 0 GOTO FINISH
LOCATE 16, 3, 1
COLOR 3
GET (0, 230)-(639, 265), BOX%
LINE (0, 230)-(639, 265), 2, BF
LINE (5, 235)-(634, 260), 1, BF
LINE (10, 240)-(630, 255), 0, BF
PRINT MESSAGE$;
BEGIN:
A$ = UCASE$(INKEY$)
IF LEN(EXIT$) = LENTH% AND ENTER% = 0 GOTO FINISH
IF A$ = "" GOTO BEGIN
IF A$ = CHR$(13) GOTO FINISH
IF A$ = CHR$(27) THEN EXIT$ = "": GOTO FINISH
IF A$ = CHR$(8) AND LEN(EXIT$) THEN EXIT$ = LEFT$(EXIT$, LEN(EXIT$) - 1): IF ECHO% THEN LOCATE , POS(0) - 1: PRINT CHR$(32); : LOCATE , POS(0) - 1
IF LEN(EXIT$) = LENTH% GOTO BEGIN
IF A$ = CHR$(32) AND SPACE% THEN YES = 1
IF ASC(A$) > 64 AND ASC(A$) < 91 AND LETTERS% THEN YES = 1
IF ASC(A$) > 47 AND ASC(A$) < 58 AND NUMBERS% THEN YES = 1
IF YES = 0 GOTO BEGIN
YES = 0
EXIT$ = EXIT$ + A$
IF ECHO% THEN PRINT A$;
GOTO BEGIN
FINISH:
IF FLAG% = 1 THEN EXIT SUB
PUT (0, 230), BOX%, PSET
END SUB

SUB ITEM.SCAN (FLAG&)
IF FLAG& = 16 THEN ITEM$ = "KEYS"
IF FLAG& = 32 THEN ITEM$ = "POPCANS"
IF FLAG& = 64 THEN ITEM$ = "HEALTHS"
IF FLAG& = 128 THEN ITEM$ = "SHIELDS"
IF FLAG& = 256 THEN ITEM$ = "TIME BONUSES"
IF FLAG& = 512 THEN ITEM$ = "MONSTERS"
IF FLAG& = 1024 THEN ITEM$ = "GUNS"
IF FLAG& = 2048 THEN ITEM$ = "BOMBS"
IF FLAG& = 4096 THEN ITEM$ = "DOORS"
IF FLAG& = 8192 THEN ITEM$ = "LANTERNS"
IF FLAG& = 16384 THEN ITEM$ = "EXITS"
IF FLAG& = 32768 THEN ITEM$ = "WARP START"
IF FLAG& = 65536 THEN ITEM$ = "WARP EXIT"
FOR X% = 1 TO 20
FOR Y% = 1 TO 20
ITEM& = (CHART&(X%, Y%) AND FLAG&)
IF ITEM& = FLAG& THEN LINE (X% * 20 + 5, Y% * 20 + 5)-(X% * 20 + 15, Y% * 20 + 15), 5, BF: ITEM.FOUND% = 1
IF (CHART&(X%, Y%) AND 1) THEN LINE (X% * 20 + 9, Y% * 20 + 1)-(X% * 20 + 11, Y% * 20 + 10), 2, BF
IF (CHART&(X%, Y%) AND 2) THEN LINE (X% * 20 + 1, Y% * 20 + 9)-(X% * 20 + 10, Y% * 20 + 11), 2, BF
IF (CHART&(X%, Y%) AND 4) THEN LINE (X% * 20 + 10, Y% * 20 + 9)-(X% * 20 + 19, Y% * 20 + 11), 2, BF
IF (CHART&(X%, Y%) AND 8) THEN LINE (X% * 20 + 9, Y% * 20 + 10)-(X% * 20 + 11, Y% * 20 + 19), 2, BF
NEXT Y%
NEXT X%
IF ITEM.FOUND% = 0 THEN
NAME$ = "NO " + ITEM$ + " ARE FOUND!  PRESS ENTER."
INPUTBOX NAME$, 0, 0, 1, 0, 0, 0, 2
EXIT SUB
END IF
COLOR 14
LOCATE 15, 60: PRINT "SHOWING "; ITEM$
LOCATE 16, 60: PRINT "PRESS ANY KEY..."
DO: LOOP UNTIL INKEY$ = ""
DO: LOOP UNTIL INKEY$ <> ""
LOCATE 15, 60: PRINT "                    "
LOCATE 16, 60: PRINT "                    "
FOR X% = 1 TO 20
FOR Y% = 1 TO 20
ITEM& = (CHART&(X%, Y%) AND FLAG&)
IF ITEM& = FLAG& THEN LINE (X% * 20 + 5, Y% * 20 + 5)-(X% * 20 + 15, Y% * 20 + 15), 0, BF
IF (CHART&(X%, Y%) AND 1) THEN LINE (X% * 20 + 9, Y% * 20 + 1)-(X% * 20 + 11, Y% * 20 + 10), 2, BF
IF (CHART&(X%, Y%) AND 2) THEN LINE (X% * 20 + 1, Y% * 20 + 9)-(X% * 20 + 10, Y% * 20 + 11), 2, BF
IF (CHART&(X%, Y%) AND 4) THEN LINE (X% * 20 + 10, Y% * 20 + 9)-(X% * 20 + 19, Y% * 20 + 11), 2, BF
IF (CHART&(X%, Y%) AND 8) THEN LINE (X% * 20 + 9, Y% * 20 + 10)-(X% * 20 + 11, Y% * 20 + 19), 2, BF
NEXT Y%
NEXT X%
END SUB

SUB LOAD.MAP
IF CHANGES.MADE% THEN SAVE.MAP 1
IF CHANGES.MADE% THEN EXIT SUB
INPUT.FILE:
INPUTBOX "LOAD FROM A FILE NAMED:  ", 8, 1, 1, 1, 1, 0, 2
IF EXIT$ = "" THEN EXIT SUB
FILENAME$ = EXIT$ + ".ICN"
ON ERROR GOTO NEW.FILE:
FILE.ERR% = 0
OPEN FILENAME$ FOR INPUT AS #1
CLOSE #1
IF FILE.ERR% = 1 GOTO FILE.NOT.FOUND
OPEN FILENAME$ FOR APPEND AS #1
VERSION& = LOC(1)
CLOSE #1
IF VERSION& = 14 THEN GOTO FILE.LOAD
NAME$ = "FILE NAMED " + CHR$(34) + FILENAME$ + CHR$(34) + " IS OF INCORRECT FORMAT!  LOAD ANYWAY?(Y/N)"
INPUTBOX NAME$, 1, 0, 0, 1, 0, 0, 2
IF EXIT$ = "Y" GOTO FILE.LOAD
EXIT SUB
FILE.NOT.FOUND:
NAME$ = "FILE NAMED " + CHR$(34) + FILENAME$ + CHR$(34) + " DOES NOT EXIST!  PRESS ENTER."
INPUTBOX NAME$, 0, 0, 1, 0, 0, 0, 2
GOTO INPUT.FILE
FILE.LOAD:
DEF SEG = VARSEG(CHART&(0, 0))
BLOAD FILENAME$, VARPTR(CHART&(0, 0))
WORKING.FILE$ = FILENAME$
COLOR 15
LOCATE 1, 23: PRINT WORKING.FILE$; SPC(7);
FOR X% = 1 TO 20
FOR Y% = 1 TO 20
LINE (X% * 20 + 1, Y% * 20 + 1)-(X% * 20 + 19, Y% * 20 + 19), 0, BF
IF (CHART&(X%, Y%) AND 1) THEN LINE (X% * 20 + 9, Y% * 20 + 1)-(X% * 20 + 11, Y% * 20 + 10), 2, BF
IF (CHART&(X%, Y%) AND 2) THEN LINE (X% * 20 + 1, Y% * 20 + 9)-(X% * 20 + 10, Y% * 20 + 11), 2, BF
IF (CHART&(X%, Y%) AND 4) THEN LINE (X% * 20 + 10, Y% * 20 + 9)-(X% * 20 + 19, Y% * 20 + 11), 2, BF
IF (CHART&(X%, Y%) AND 8) THEN LINE (X% * 20 + 9, Y% * 20 + 10)-(X% * 20 + 11, Y% * 20 + 19), 2, BF
NEXT Y%
NEXT X%
GO% = 1
DEF SEG = 0
END SUB

SUB MAINLOOP
X% = 1
Y% = 1
GO% = 1
DEF SEG = 0
MAINLOOP:
A$ = UCASE$(INKEY$)
ALT% = (PEEK(1047) AND 8)
KEYB% = INP(96):
IF MODE% = 0 AND A$ = CHR$(27) GOTO ENDER
SX% = X%
SY% = Y%
COLOR 15
IF KEYB% = 6 AND MODE% = 0 THEN
MODE% = 1
LOCATE 1, 55
LOCATE 28, 1: PRINT "                         ESC TO EXIT WARP EDIT MODE                   "
LOCATE 1, 55: PRINT "PRESS DESIRED KEY"
LOCATE , 55: PRINT "1 TO SET WARP ENTRANCE"
LOCATE , 55: PRINT "2 TO SET WARP DESTINATION"
WAIT.FOR.KEY.RELEASE KEYB%
GOTO MAINLOOP
END IF
IF KEYB% = 1 AND MODE% = 1 THEN
MODE% = 0
LOCATE 28, 1
PRINT "1-save  2-load 3-new 4-display mode 5-warp mode"
LOCATE 1, 55: PRINT "                         "
LOCATE , 55: PRINT "                         "
LOCATE , 55: PRINT "                         "
WAIT.FOR.KEY.RELEASE KEYB%
END IF
IF MODE% = 1 AND KEYB% > 1 AND KEYB% < 4 THEN EDIT.WARP KEYB%, X%, Y%
IF MODE% = 0 AND KEYB% = 2 THEN SAVE.MAP 0
IF MODE% = 0 AND KEYB% = 3 THEN LOAD.MAP
IF MODE% = 0 AND KEYB% = 4 THEN NEW.MAP
IF MODE% = 0 AND KEYB% = 5 THEN SHOW.ME
IF MODE% = 0 AND ALT% = 8 AND KEYB% = 77 THEN CHART&(X%, Y%) = (CHART&(X%, Y%) XOR 4): GO% = 3
IF MODE% = 0 AND ALT% = 8 AND KEYB% = 75 THEN CHART&(X%, Y%) = (CHART&(X%, Y%) XOR 2): GO% = 3
IF MODE% = 0 AND ALT% = 8 AND KEYB% = 80 THEN CHART&(X%, Y%) = (CHART&(X%, Y%) XOR 8): GO% = 3
IF MODE% = 0 AND ALT% = 8 AND KEYB% = 72 THEN CHART&(X%, Y%) = (CHART&(X%, Y%) XOR 1): GO% = 3
IF NOT X% = 20 AND A$ = CHR$(0) + "M" THEN X% = X% + 1: GO% = 1
IF NOT X% = 1 AND A$ = CHR$(0) + "K" THEN X% = X% - 1: GO% = 1
IF NOT Y% = 1 AND A$ = CHR$(0) + "H" THEN Y% = Y% - 1: GO% = 1
IF NOT Y% = 20 AND A$ = CHR$(0) + "P" THEN Y% = Y% + 1: GO% = 1
IF MODE% = 0 AND A$ = CHR$(32) THEN CHANGE.ITEM X%, Y%: GO% = 2
IF GO% = 1 THEN LINE (SX% * 20, SY% * 20)-(SX% * 20 + 20, SY% * 20 + 20), 1, B
IF GO% = 1 THEN LINE (X% * 20, Y% * 20)-(X% * 20 + 20, Y% * 20 + 20), 2, B
IF GO% = 3 THEN CHANGES.MADE% = 1
IF GO% > 0 AND GO% < 3 THEN SHOW.ITEM X%, Y%: GO% = 0
IF GO% = 3 THEN UPDATE.ROOM X%, Y%: GO% = 0
IF ALT% THEN WAIT.FOR.KEY.RELEASE KEYB%
ALT% = 0
GOTO MAINLOOP
ENDER:
IF CHANGES.MADE% THEN SAVE.MAP 1: IF EXIT$ = "" GOTO MAINLOOP
INPUTBOX "EXIT THIS [HA] GREAT PROGRAM?(Y/N)", 1, 0, 0, 1, 0, 0, 2
IF EXIT$ <> "Y" GOTO MAINLOOP
END SUB

SUB NEW.MAP
IF CHANGES.MADE% = 0 AND WORKING.FILE$ = "UNTITLED" THEN EXIT SUB
IF CHANGES.MADE% THEN SAVE.MAP 1
IF CHANGES.MADE% THEN EXIT SUB
FOR X% = 1 TO 20
FOR Y% = 1 TO 20
LINE (X% * 20 + 1, Y% * 20 + 1)-(X% * 20 + 19, Y% * 20 + 19), 0, BF
CHART&(X%, Y%) = 0
NEXT Y%
NEXT X%
WORKING.FILE$ = "UNTITLED"
COLOR 15
LOCATE 1, 23: PRINT WORKING.FILE$; SPC(7);
GO% = 1
CHANGES.MADE% = 0
END SUB

SUB SAVE.MAP (FLAG%)
IF FLAG% = 0 GOTO INPUT.FILENAME
IF CHANGES.MADE% = 0 THEN GOTO INPUT.FILENAME
CHANGE.FILE:
INPUTBOX "CHANGES HAVE BEEN MADE.  SAVE NOW?(Y/N):  ", 1, 0, 0, 1, 0, 0, 2
IF EXIT$ = "" THEN EXIT SUB
IF EXIT$ <> "Y" AND EXIT$ <> "N" GOTO CHANGE.FILE
IF EXIT$ = "N" THEN CHANGES.MADE% = 0: EXIT SUB
INPUT.FILENAME:
INPUTBOX "SAVE TO A FILE NAMED:  ", 8, 1, 1, 1, 1, 0, 2
IF EXIT$ = "" THEN EXIT SUB
EXIT$ = EXIT$ + ".ICN"
FILENAME$ = EXIT$
ON ERROR GOTO NEW.FILE:
OPEN EXIT$ FOR INPUT AS #1
CLOSE #1
IF FILE.ERR% = 1 GOTO FILE.SAVE
NAME$ = "OVERWRITE FILE NAMED " + CHR$(34) + EXIT$ + CHR$(34) + "?(Y/N)"
INPUTBOX NAME$, 1, 1, 0, 1, 0, 0, 2
IF NOT EXIT$ = "Y" THEN EXIT SUB
FILE.SAVE:
DEF SEG = VARSEG(CHART&(0, 0))
BSAVE FILENAME$, 0, VARPTR(CHART&(20, 21))
WORKING.FILE$ = FILENAME$
COLOR 15
LOCATE 1, 23: PRINT WORKING.FILE$; SPC(7);
NAME$ = "FILE NAMED " + CHR$(34) + FILENAME$ + CHR$(34) + " HAS BEEN SAVED. PRESS ENTER."
INPUTBOX NAME$, 0, 0, 1, 0, 0, 0, 2
CHANGES.MADE% = 0
DEF SEG = 0
END SUB

SUB SHOW.ITEM (X%, Y%)
COLOR 14
LOCATE 23, 64
IF CHART&(X%, Y%) < 16 THEN PRINT "          ": EXIT SUB
IF (CHART&(X%, Y%) AND 16) = 16 THEN PRINT "   KEY    ": EXIT SUB
IF (CHART&(X%, Y%) AND 32) = 32 THEN PRINT "  POPCAN  ": EXIT SUB
IF (CHART&(X%, Y%) AND 64) = 64 THEN PRINT "  HEALTH  ": EXIT SUB
IF (CHART&(X%, Y%) AND 128) = 128 THEN PRINT "  SHIELD  ": EXIT SUB
IF (CHART&(X%, Y%) AND 256) = 256 THEN PRINT "TIME BONUS": EXIT SUB
IF (CHART&(X%, Y%) AND 512) = 512 THEN PRINT "  MONSTER ": EXIT SUB
IF (CHART&(X%, Y%) AND 1024) = 1024 THEN PRINT "   GUN    ": EXIT SUB
IF (CHART&(X%, Y%) AND 2048) = 2048 THEN PRINT "   BOMB   ": EXIT SUB
IF (CHART&(X%, Y%) AND 4096) = 4096 THEN PRINT "   DOOR   ": EXIT SUB
IF (CHART&(X%, Y%) AND 8192) = 8192 THEN PRINT "  LANTERN ": EXIT SUB
IF (CHART&(X%, Y%) AND 16384) = 16384 THEN PRINT "   EXIT   ": EXIT SUB
IF (CHART&(X%, Y%) AND 32768) = 32768 THEN PRINT "WARP START": EXIT SUB
IF (CHART&(X%, Y%) AND 65536) = 65536 THEN PRINT "WARP  EXIT": EXIT SUB
END SUB

SUB SHOW.ME
COLOR 15
LOCATE 28, 1: PRINT "                         ESC TO EXIT DISPLAY MODE                   "
LOCATE 1, 55: PRINT "PRESS DESIRED KEY"
LOCATE , 55: PRINT "1  TO  SHOW KEYS"
LOCATE , 55: PRINT "2  TO  SHOW POPCANS"
LOCATE , 55: PRINT "3  TO  SHOW HEALTHS"
LOCATE , 55: PRINT "4  TO  SHOW SHIELDS"
LOCATE , 55: PRINT "5  TO  SHOW TIME BONUS"
LOCATE , 55: PRINT "6  TO  SHOW MONSTERS"
LOCATE , 55: PRINT "7  TO  SHOW GUNS"
LOCATE , 55: PRINT "8  TO  SHOW BOMBS"
LOCATE , 55: PRINT "9  TO  SHOW DOORS"
LOCATE , 55: PRINT "0  TO  SHOW LANTERNS"
LOCATE , 55: PRINT "-  TO  SHOW EXITS"
LOCATE , 55: PRINT "=  TO  SHOW WARP START"
LOCATE , 55: PRINT "\  TO  SHOW WARP EXIT"
DO: LOOP UNTIL INKEY$ = ""
DO
KEYB$ = INKEY$
IF KEYB$ = "1" THEN ITEM.SCAN 16
IF KEYB$ = "2" THEN ITEM.SCAN 32
IF KEYB$ = "3" THEN ITEM.SCAN 64
IF KEYB$ = "4" THEN ITEM.SCAN 128
IF KEYB$ = "5" THEN ITEM.SCAN 256
IF KEYB$ = "6" THEN ITEM.SCAN 512
IF KEYB$ = "7" THEN ITEM.SCAN 1024
IF KEYB$ = "8" THEN ITEM.SCAN 2048
IF KEYB$ = "9" THEN ITEM.SCAN 4096
IF KEYB$ = "0" THEN ITEM.SCAN 8192
IF KEYB$ = "-" THEN ITEM.SCAN 16384
IF KEYB$ = "=" THEN ITEM.SCAN 32768
IF KEYB$ = "\" THEN ITEM.SCAN 65536
IF KEYB$ = CHR$(27) THEN EXIT DO
LOOP
COLOR 15
LOCATE 1
FOR REMOVE% = 1 TO 14
LOCATE , 55
PRINT "                      "
NEXT REMOVE%
LOCATE 1, 23: PRINT WORKING.FILE$
LOCATE 28, 1: PRINT "F1 = SAVE MAP", "F2 = LOAD MAP", "F3 = NEW MAP", "F4 = DISPLAY MODE"
END SUB

SUB SHOW.SWITCH

END SUB

SUB SHOW.WARP
X% = CHART&(0, 4)
Y% = CHART&(0, 5)
IF CHART&(0, 2) = 0 OR CHART&(0, 3) = 0 OR CHART&(0, 4) = 0 OR CHART&(0, 5) = 0 THEN
NAME$ = "WARP ENTRANCE AND/OR DESTINATION NOT SET!  PRESS ENTER."
INPUTBOX NAME$, 0, 0, 1, 0, 0, 0, 2
EXIT SUB
END IF
COLOR 14
LOCATE 15, 60: PRINT "SHOWING WARP"
LOCATE , 55: PRINT "RED DOT IS ENTRANCE"
LOCATE , 55: PRINT "BLUE DOT IS DESTINATION"
LOCATE , 60: PRINT "PRESS ANY KEY..."
X% = CHART&(0, 2)
Y% = CHART&(0, 3)
LINE (X% * 20 + 5, Y% * 20 + 5)-(X% * 20 + 15, Y% * 20 + 15), 12, BF
IF (CHART&(X%, Y%) AND 1) THEN LINE (X% * 20 + 9, Y% * 20 + 1)-(X% * 20 + 11, Y% * 20 + 10), 2, BF
IF (CHART&(X%, Y%) AND 2) THEN LINE (X% * 20 + 1, Y% * 20 + 9)-(X% * 20 + 10, Y% * 20 + 11), 2, BF
IF (CHART&(X%, Y%) AND 4) THEN LINE (X% * 20 + 10, Y% * 20 + 9)-(X% * 20 + 19, Y% * 20 + 11), 2, BF
IF (CHART&(X%, Y%) AND 8) THEN LINE (X% * 20 + 9, Y% * 20 + 10)-(X% * 20 + 11, Y% * 20 + 19), 2, BF
X% = CHART&(0, 4)
Y% = CHART&(0, 5)
LINE (X% * 20 + 5, Y% * 20 + 5)-(X% * 20 + 15, Y% * 20 + 15), 9, BF
IF (CHART&(X%, Y%) AND 1) THEN LINE (X% * 20 + 9, Y% * 20 + 1)-(X% * 20 + 11, Y% * 20 + 10), 2, BF
IF (CHART&(X%, Y%) AND 2) THEN LINE (X% * 20 + 1, Y% * 20 + 9)-(X% * 20 + 10, Y% * 20 + 11), 2, BF
IF (CHART&(X%, Y%) AND 4) THEN LINE (X% * 20 + 10, Y% * 20 + 9)-(X% * 20 + 19, Y% * 20 + 11), 2, BF
IF (CHART&(X%, Y%) AND 8) THEN LINE (X% * 20 + 9, Y% * 20 + 10)-(X% * 20 + 11, Y% * 20 + 19), 2, BF
DO: LOOP UNTIL INKEY$ = ""
DO: LOOP UNTIL INKEY$ <> ""
LOCATE 15, 55: PRINT "                       "
LOCATE , 55: PRINT "                         "
LOCATE , 55: PRINT "                       "
LOCATE , 55: PRINT "                         "
FOR X% = 1 TO 20
FOR Y% = 1 TO 20
ITEM& = (CHART&(X%, Y%) AND FLAG&)
IF ITEM& = FLAG& THEN LINE (X% * 20 + 5, Y% * 20 + 5)-(X% * 20 + 15, Y% * 20 + 15), 0, BF
IF (CHART&(X%, Y%) AND 1) THEN LINE (X% * 20 + 9, Y% * 20 + 1)-(X% * 20 + 11, Y% * 20 + 10), 2, BF
IF (CHART&(X%, Y%) AND 2) THEN LINE (X% * 20 + 1, Y% * 20 + 9)-(X% * 20 + 10, Y% * 20 + 11), 2, BF
IF (CHART&(X%, Y%) AND 4) THEN LINE (X% * 20 + 10, Y% * 20 + 9)-(X% * 20 + 19, Y% * 20 + 11), 2, BF
IF (CHART&(X%, Y%) AND 8) THEN LINE (X% * 20 + 9, Y% * 20 + 10)-(X% * 20 + 11, Y% * 20 + 19), 2, BF
NEXT Y%
NEXT X%

END SUB

DEFSNG A-Z
SUB START
WIDTH 80, 43
DEF SEG = -18432
'BLOAD "mapmaker.hlp", 0
LOCATE 41, 30: PRINT "Press a key..."
DO: LOOP UNTIL INKEY$ = ""
DO: LOOP UNTIL INKEY$ <> ""
SCREEN 12
WORKING.FILE$ = "UNTITLED"
FOR X% = 1 TO 20
FOR Y% = 1 TO 20
LINE (X% * 20, Y% * 20)-(X% * 20 + 20, Y% * 20 + 20), 1, B
NEXT Y%
NEXT X%
LOCATE 1, 23: PRINT WORKING.FILE$
LOCATE 28, 1
PRINT "1-save  2-load 3-new 4-display mode 5-warp mode"
LINE (500, 320)-(590, 410), 2, B
LOCATE 20, 63: PRINT "ITEM IN ROOM"
LOCATE 27, 59: PRINT "PRESS SPACE TO CHANGE"
MAINLOOP
END SUB

DEFINT A-Z
SUB UPDATE.ROOM (X%, Y%)
IF (CHART&(X%, Y%) AND 1) = 0 THEN LINE (X% * 20 + 9, Y% * 20 + 1)-(X% * 20 + 11, Y% * 20 + 10), 0, BF
IF (CHART&(X%, Y%) AND 2) = 0 THEN LINE (X% * 20 + 1, Y% * 20 + 9)-(X% * 20 + 10, Y% * 20 + 11), 0, BF
IF (CHART&(X%, Y%) AND 4) = 0 THEN LINE (X% * 20 + 10, Y% * 20 + 9)-(X% * 20 + 19, Y% * 20 + 11), 0, BF
IF (CHART&(X%, Y%) AND 8) = 0 THEN LINE (X% * 20 + 9, Y% * 20 + 10)-(X% * 20 + 11, Y% * 20 + 19), 0, BF
IF (CHART&(X%, Y%) AND 1) THEN LINE (X% * 20 + 9, Y% * 20 + 1)-(X% * 20 + 11, Y% * 20 + 10), 2, BF
IF (CHART&(X%, Y%) AND 2) THEN LINE (X% * 20 + 1, Y% * 20 + 9)-(X% * 20 + 10, Y% * 20 + 11), 2, BF
IF (CHART&(X%, Y%) AND 4) THEN LINE (X% * 20 + 10, Y% * 20 + 9)-(X% * 20 + 19, Y% * 20 + 11), 2, BF
IF (CHART&(X%, Y%) AND 8) THEN LINE (X% * 20 + 9, Y% * 20 + 10)-(X% * 20 + 11, Y% * 20 + 19), 2, BF
END SUB

SUB WAIT.FOR.KEY.RELEASE (KEYB%)
DO
DO: LOOP UNTIL INKEY$ = ""
PASS:
LOOK% = INP(96)
IF LOOK% = 224 GOTO PASS
IF LOOK% <> KEYB% THEN EXIT DO
LOOP
END SUB

